#107 Ensure that env variable PODMAN_BIN wins
konveyor/kantra pull request #108
Opened 2023-11-01 15:56 UTC by ascheman

As discussed [via Slack](https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1698853574068369?thread_ts=1698830510.500689&cid=C04QZJFQ0UA)

2023-11-01 17:06 UTC, pranavgaikwad approved these changes
LGTM

2023-11-01 17:06 UTC, pranavgaikwad commented on cmd/settings.go
> +	var envValue = os.Getenv("PODMAN_BIN")
you might know this already...idiomatic way of initiating a variable with value is: 

```
envValue := os.Getenv("PODMAN_BIN")
```

2023-11-01 17:06 UTC, pranavgaikwad requested changes
Requires signing off

2023-11-01 18:17 UTC, eemcmullan approved these changes

2023-11-02 13:11 UTC, shawn-hurley commented on cmd/settings.go
> +		podmanPath, _ := exec.LookPath("podman")
Worried about eating the error here

It does seem that LookPath has some interesting edge case:

> In older versions of Go, LookPath could return a path relative to the current directory. As of Go 1.19, LookPath will instead return that path along with an error satisfying errors.Is(err, ErrDot). See the package documentation for more details.

Can you also add a check if err is not nil && err is not ErrDot? if it is error I think this means that Rodman is not installed and we can error out noting that. @pranavgaikwad and @eemcmullan will defer to y'all if I understood that correctly :)

2023-11-02 14:21 UTC, eemcmullan commented on cmd/settings.go
> +		podmanPath, _ := exec.LookPath("podman")
I think this sounds smart. I don't remember the original intention behind masking the error here, but +1 on checking for those two.

2023-11-08 10:37 UTC, ascheman commented on cmd/settings.go
> +		podmanPath, _ := exec.LookPath("podman")
I would like to concentrate on correct handling of the PODMAN_BIN variable here, as the bug #107 and the PR #108 is about that problem. If you want to check whether `podman` is installed at all and abort Kantra when this is not the case, this is a different concern. OK?

2023-11-08 14:45 UTC, shawn-hurley approved these changes

2023-11-08 14:45 UTC, shawn-hurley commented on cmd/settings.go
> +		podmanPath, _ := exec.LookPath("podman")
Considering that this was prior behavior, I think it is reasonable that we can do it in a follow up, sorry just caught it now, but that makes sense. 

Created a follow up issue: https://github.com/konveyor/kantra/issues/113

2023-11-08 14:47 UTC, pranavgaikwad approved these changes

2023-11-09 12:20 UTC, merged

2023-11-09 12:27 UTC, ascheman commented
Thanks!