use err for lookpath
konveyor/kantra pull request #118
Opened 2023-11-10 16:43 UTC by eemcmullan

Closes #113

2023-11-15 18:55 UTC, pranavgaikwad requested changes

2023-11-15 18:55 UTC, pranavgaikwad commented on cmd/settings.go
> +			return err
I think the idea was to only error when you see a `errors.Is(err, ErrDot)`

2023-11-21 18:58 UTC, eemcmullan commented on cmd/settings.go
> +			return err
@pranavgaikwad  Looks like `exec.ErrDot` requires go 1.19: https://pkg.go.dev/os/exec 
We may need to update the Dockerfile too?

2023-11-21 20:55 UTC, pranavgaikwad commented on cmd/settings.go
> +			return err
yes, analyzer-lsp is using 19 as well

2023-11-27 05:02 UTC, pranavgaikwad approved these changes

2023-11-27 15:01 UTC, merged