MTA-2041: send err to analysis command
konveyor/kantra pull request #149
Opened 2024-01-23 21:14 UTC by eemcmullan

Because we send errs to logs: https://github.com/konveyor/kantra/blob/main/cmd/analyze.go#L746 the errors hit during analysis or shim would not bubble up to the analyze command itself: https://github.com/konveyor/kantra/blob/main/cmd/analyze.go#L128 

Closes #148

2024-01-24 17:44 UTC, pranavgaikwad requested changes

2024-01-24 18:33 UTC, eemcmullan commented on cmd/analyze.go
> -				log.Error(err, "failed to convert xml rules")
Will take a look there

2024-01-25 18:12 UTC, shawn-hurley commented on cmd/analyze.go
> -				log.Error(err, "failed to convert xml rules")
it might be worth adding a flag, that can say print to stderr on failure for all of the commands (shim/lsp/dep).

2024-01-25 18:50 UTC, eemcmullan commented on cmd/analyze.go
> -				log.Error(err, "failed to convert xml rules")
The issue is that without sending the error to stderr, the error on output is blank like so:

```
ERRO[0042] container run error                           error="exit status 1"
Error:
```

Instead of a flag, maybe we need to force this?

2024-02-01 14:54 UTC, eemcmullan commented
closing for fix in analyzer-lsp https://github.com/konveyor/analyzer-lsp/issues/479

2024-02-01 14:54 UTC, closed without merging