Override container runtime for commands
konveyor/kantra pull request #181
Opened 2024-03-19 19:11 UTC by eemcmullan

2024-03-19 19:29 UTC, pranavgaikwad requested changes

2024-03-19 19:29 UTC, pranavgaikwad commented on cmd/analyze.go
> +			container.WithContainerRuntimeBin(os.Getenv("PODMAN_BIN")),
can we rename containerRuntime to containerTool everywhere as it's not accurate? also, should we be using the PODMAN_BIN from the settings as we have some logic to auto-detect things too?

2024-03-19 19:31 UTC, pranavgaikwad commented
@eemcmullan I also think that this should not cherry-picked because this is introduced in my most recent fix which itself isn't cherry-picked (it is for 0.4)

2024-03-19 20:04 UTC, shawn-hurley commented on cmd/analyze.go
> +			container.WithContainerRuntimeBin(os.Getenv("PODMAN_BIN")),
I am plus one on the re-name myself

2024-03-20 15:40 UTC, pranavgaikwad approved these changes

2024-03-20 16:51 UTC, shawn-hurley approved these changes

2024-03-20 17:30 UTC, merged