Run Java provider in separate container
konveyor/kantra pull request #194
Opened 2024-04-15 15:56 UTC by eemcmullan

This will need to be updated for multiple provider containers once we accept multiple inputs

2024-04-16 13:24 UTC, pranavgaikwad commented on Dockerfile
> +# java-external-provider port
Do we plan to keep the port hardcoded or pass it at runtime to entrypoint?

2024-04-16 13:26 UTC, pranavgaikwad commented on cmd/openrewrite.go
> +	_, err := container.NewContainer().Run(
I think you can just get the name of the container by accessing the container object returned by NewContainer(), don't think you need to return it in Run

2024-04-17 01:16 UTC, eemcmullan commented on Dockerfile
> +# java-external-provider port
Have the user pass it? Or we create a new random port and pass that?

2024-04-17 01:18 UTC, eemcmullan commented on cmd/openrewrite.go
> +	_, err := container.NewContainer().Run(
The issue is that we need the container name of the first provider's container so that we can join other providers/analyzer engine to that container's network.

2024-04-17 12:23 UTC, pranavgaikwad commented on cmd/openrewrite.go
> +	_, err := container.NewContainer().Run(
why wouldn't this work:
```
c := container.NewContainer()
firstContainerName := c.name
err := c.Run()
```

2024-04-17 12:24 UTC, pranavgaikwad commented on Dockerfile
> +# java-external-provider port
create random port...see freeport library https://github.com/konveyor/analyzer-lsp/blob/970202dcec72983dd82977eef2996a626e625033/provider/grpc/provider.go#L132

2024-04-22 15:36 UTC, pranavgaikwad requested changes

2024-04-22 15:36 UTC, pranavgaikwad commented on Dockerfile
> +FROM quay.io/konveyor/java-external-provider:latest as java-provider
now that we already publish separate images for providers, do we need them in the kantra image?

2024-04-22 15:36 UTC, pranavgaikwad commented on cmd/analyze.go
> +				go func() {
why run two different functions in defer? can't it be just in defer and we don't have to wait?

2024-04-22 15:36 UTC, pranavgaikwad commented on cmd/analyze.go
> +			fmt.Printf("FOUND PROVIDERS!! %v \n", foundProviders)
remove fmt.Printf or if its meant to print to stdout, can we remove the !!

2024-04-22 15:36 UTC, pranavgaikwad commented on cmd/settings.go
> +const (
We need to be able to load these from env var

2024-04-22 15:42 UTC, shawn-hurley approved these changes
Just some questions and small nits but LGTM besides

2024-04-22 15:42 UTC, shawn-hurley commented on cmd/analyze.go
> +				wg.Wait()
Is there a place in time where these will not run or won't be able to error because the main process exits?

2024-04-22 15:42 UTC, shawn-hurley commented on cmd/analyze.go
> +			fmt.Printf("FOUND PROVIDERS!! %v \n", foundProviders)
nit: probably was left over from my PR, but we should remove :)

2024-04-22 15:42 UTC, shawn-hurley commented on cmd/analyze.go
> +	port, err := freeport.GetFreePort()
is free port working on the host network but it probably needs to work on container network?

This is more of a question

2024-04-22 15:42 UTC, shawn-hurley commented on cmd/analyze.go
> +	default:
should we exit early here for now?

2024-04-22 15:42 UTC, shawn-hurley commented on cmd/analyze.go
> +	// we need to start each provider container separately from the first one so that
nit: delete?

2024-04-22 15:42 UTC, shawn-hurley commented on pkg/container/container.go
> +	Name           string
why exporting?

2024-04-22 16:20 UTC, eemcmullan commented on pkg/container/container.go
> +	Name           string
It is how the analyzer engine connects to the provider's network when the analyzer container is first created. I think the `network connect` command requires the container to already be running, which I think may complicate things, since the analyzer container needs to start after the provider container.

2024-04-22 16:32 UTC, shawn-hurley commented on pkg/container/container.go
> +	Name           string
I see makes sense

2024-04-22 18:45 UTC, eemcmullan commented on cmd/analyze.go
> +				wg.Wait()
removing this logic

2024-04-22 20:52 UTC, pranavgaikwad requested changes
one small request, then this is good to go unless Shawn has something

2024-04-22 20:52 UTC, pranavgaikwad commented on Dockerfile
> +RUN go install golang.org/x/tools/gopls@latest
is this needed?

2024-04-23 01:27 UTC, eemcmullan commented on Dockerfile
> +RUN go install golang.org/x/tools/gopls@latest
Forgot to remove it with the added provider images

2024-04-23 02:34 UTC, eemcmullan commented on cmd/analyze.go
> +	port, err := freeport.GetFreePort()
Good point. I'm trying to think of a way around this. The provider container needs the port as it starts, so we would not be able to first run the provider and then check if a port is in use for that container. And I think we moved away from hard-coding in the ports. My only other thought would be to catch the error and try to run the container again.

2024-04-23 12:29 UTC, pranavgaikwad approved these changes

2024-04-23 14:02 UTC, aufi approved these changes
ack

2024-04-23 14:10 UTC, shawn-hurley commented on cmd/analyze.go
> +	port, err := freeport.GetFreePort()
I think that may make sense, I was hoping that you could point Freeport to a specific network, but catch err is probably the best approach for now

2024-04-23 14:10 UTC, shawn-hurley commented
Except for the Freeport part /LGTM

2024-04-23 20:10 UTC, pranavgaikwad commented on cmd/analyze.go
> +		if err.Error() == "bind: address already in use" {
can we just retry 5 times without worrying about what the error is...I am a bit worried about relying on error strings.

2024-04-24 13:52 UTC, merged