Add NodeJS and Python providers
konveyor/kantra pull request #218
Opened 2024-05-01 20:39 UTC by eemcmullan

2024-05-02 14:14 UTC, shawn-hurley commented on cmd/analyze.go
> +	if !a.analyzeKnownLibraries && (providers[0] != pythonProvider && providers[0] != nodeJSProvider) {
We eventually need to not hard code this but be able to tell from the provider caps IMO

2024-05-02 14:14 UTC, shawn-hurley commented on cmd/analyze.go
> +	if !a.analyzeKnownLibraries && (providers[0] != pythonProvider && providers[0] != nodeJSProvider) {
there is nothing to do right now, but something to consider in the future that I didn't want to lose track off

2024-05-03 14:10 UTC, eemcmullan commented on cmd/analyze.go
> +	if !a.analyzeKnownLibraries && (providers[0] != pythonProvider && providers[0] != nodeJSProvider) {
@shawn-hurley https://github.com/konveyor/analyzer-lsp/issues/597

2024-05-03 15:57 UTC, shawn-hurley commented
I am wondering if this can be used for the .m2 cache for the Java providers as well.

2024-05-03 16:15 UTC, shawn-hurley commented
Overall it looks good, the only big concern is that the python/nodejs servers also still need to have the ability to pull the deps down while initing but that should be solved in those providers.

I wonder if we call it dependency-cache-folder or something similar, the idea being that the underlying thing may add to this?

2024-05-03 16:15 UTC, shawn-hurley approved these changes
LGTM besides minor naming concern

2024-05-06 12:59 UTC, pranavgaikwad requested changes
nice work! small requests

2024-05-20 14:04 UTC, pranavgaikwad approved these changes

2024-05-21 13:40 UTC, merged