Containerless support for Java apps
konveyor/kantra pull request #338
Opened 2024-09-23 18:30 UTC by eemcmullan

**TODOs:**

- import java provider once analyzer-lsp CI is working
- default rulesets
- output logs to files
- json output
- list sources/targets

2024-09-26 15:46 UTC, shawn-hurley requested changes
Can we just run the static report from the main process rather than call the binary via script? IIUC what is happening

2024-09-26 15:46 UTC, shawn-hurley commented on cmd/analyze.go
> +	RulesetPath            = "/opt/rulesets"
What happens with these paths on windows?

2024-09-26 15:49 UTC, eemcmullan commented on cmd/analyze.go
> +	RulesetPath            = "/opt/rulesets"
These paths are only used by the analyzer container, which are linux containers anyways. They aren't used in the containerless work

2024-09-26 16:25 UTC, jmle commented on cmd/analyze-bin.go
> +		RunE: func(cmd *cobra.Command, args []string) error {
Is there any possibility of breaking this method down?

2024-09-26 16:26 UTC, jmle commented on cmd/analyze-bin.go
> +		// we need abs path to mount the file correctly
Is this comment still relevant here?

2024-09-26 16:54 UTC, eemcmullan commented
> Can we just run the static report from the main process rather than call the binary via script? IIUC what is happening

@shawn-hurley The first step of static report does run from main, which creates the output.js file. The script is there just because the second step required in generating the static report, building the dir and moving over the output.js file and then moving that dir into user output, requires a decent amount of chaining commands. Just thought the script made things more straight-forward, but could be wrong.

2024-09-26 16:54 UTC, eemcmullan commented on cmd/analyze-bin.go
> +		// we need abs path to mount the file correctly
We're not. Good catch

2024-09-27 14:30 UTC, aufi approved these changes
Overall looks good and mostly fits to the https://github.com/konveyor/enhancements/pull/196, LGTM.

2024-09-27 18:27 UTC, pranavgaikwad requested changes
Overall, code makes sense. Concern about static-report..

2024-09-27 18:27 UTC, pranavgaikwad commented on static-report.sh
> +npm clean-install &&
if I am not wrong, this is happening at runtime. I don't think we can expect the users to have npm installed. This should be a built artifact that's already present in `.kantra/static-report`. we just have to copy it into the output dir and put output.js under the copied dir.

2024-09-27 18:40 UTC, eemcmullan commented on static-report.sh
> +npm clean-install &&
@pranavgaikwad the `build` dir doesn't have to be created for each new analysis output? Sorry if that's not what you're talking about. I wasn't sure

2024-09-27 19:02 UTC, pranavgaikwad commented on static-report.sh
> +npm clean-install &&
yeah build dir is a one time process when we create a static-report release. The contents of the build directory remain constant for different analyses, the only variable is output.js file.

2024-09-27 19:07 UTC, eemcmullan commented on static-report.sh
> +npm clean-install &&
Gotcha. Apologies - misunderstood that step. Will update

2024-09-30 15:51 UTC, pranavgaikwad approved these changes

2024-09-30 16:18 UTC, shawn-hurley approved these changes

2024-09-30 19:16 UTC, merged