MTA-1309: Do not allow input and output dirs to be the same for transform rules
konveyor/kantra pull request #73
Opened 2023-09-21 18:03 UTC by eemcmullan

2023-09-22 08:13 UTC, abrugaro commented on cmd/shimconvert.go
> +			return fmt.Errorf("input rule directory and output directory must be different")
**question:** Will this error be triggered also if the paths are different but just by slashes?

Example:
* input: /path/to/folder/ (Slash at the end)
* output: /path/to/folder (No slash at the end)

Or

* input: /path\to\folder (backslashes)
* output: /path/to/folder

I'm new to Go so I don't know if the paths are being sanitized before this condition.

Thanks!

2023-09-22 12:15 UTC, pranavgaikwad commented
@eemcmullan need to update line numbers in demo-output because of https://github.com/konveyor/analyzer-lsp/commit/dca2d151b334da9b55e77ae88f4b49671989773a

2023-09-22 12:18 UTC, pranavgaikwad commented on cmd/shimconvert.go
> +			return fmt.Errorf("input rule directory and output directory must be different")
@abrugaro great point, paths indeed need to be cleaned before comparing, thank you

2023-09-22 12:20 UTC, pranavgaikwad requested changes
Clean paths, and increment line numbers by 1 in demo-output for https://github.com/konveyor/kantra/blob/9e3f53996c9e2da850b963786420c75813984d13/test-data/analysis-output.yaml#L1440 and https://github.com/konveyor/kantra/blob/9e3f53996c9e2da850b963786420c75813984d13/test-data/analysis-output.yaml#L1472

2023-09-26 15:46 UTC, pranavgaikwad approved these changes
LGTM just need DCO

2023-09-26 16:03 UTC, merged