include podman resource requirements for mac
konveyor/kantra pull request #95
Opened 2023-10-20 19:32 UTC by eemcmullan

Closes #61 
Closes #91

2023-10-20 20:47 UTC, pranavgaikwad approved these changes

2023-10-20 20:47 UTC, pranavgaikwad commented on README.md
> +podman machine set <vm_name> --cpus 4 --memory 8192
nit: 4 Gigs might be reasonable

2023-10-21 11:10 UTC, jwmatthews requested changes
I suggested a few updates to consider.

2023-10-21 11:10 UTC, jwmatthews commented on README.md
> +podman machine set <vm_name> --cpus 4 --memory 8192
Technically, I don't believe the memory/cpu has a relationship to the number of open files.
Let's update this so we don't confuse ourselves/others in future.

The memory I believe will stop analysis of large applications, but it won't help for the open file limit

As to 4GB, that sounds reasonable, I ran with 8GB out of caution, i think @hhpatel14 is using 4GB.

2023-10-21 11:10 UTC, jwmatthews commented on README.md
> +Prior to starting your podman machine, run
Lets add the info about Mac and limiting the number of open files on a volume mount and please be sure to link to this known issue to help others to be fully aware:  https://github.com/containers/podman/issues/16106#issuecomment-1317188581

Note, I think this command needs to be run after every reboot, i.e. I don't think ulimit is persisted.
Worth calling this out so the end user is aware, they may want to put the ulimit in their shell login script

2023-10-23 19:29 UTC, jwmatthews approved these changes
LGTM, thanks @eemcmullan

2023-10-23 21:45 UTC, merged